# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    # Before deploy
    - name: Before deploy1
      run: |
        mkdir -p before-deploy
        cp scripts/*.sh before-deploy
        cp appspec.yml before-deploy
        cp build/libs/*.jar before-deploy
        cd before-deploy && zip -r before-deploy ./*
        cd ../ && mkdir -p deploy
        mv before_deploy/before-deploy.zip deploy/blog.zip

    # Deploy
    - name: Deploy
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: |
        aws s3 cp ./deploy/blog.zip s3://blog-springboot-build

    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name blog-springboot-webservice
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name blog-springboot-webservice-group
        --s3-location bucket=blog-springboot-build,bundleType=zip,key=blog.zip
